name: CI

on:
  # プルリクエスト時に実行
  pull_request:
    branches: [main]
  # 他のワークフローから呼び出し可能にする
  workflow_call:
    outputs:
      build-success:
        description: "Whether the build was successful"
        value: ${{ jobs.test.outputs.build-success }}

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    outputs:
      build-success: ${{ steps.build.outcome == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run linter
        run: pnpm biome check --no-errors-on-unmatched
      
      - name: Run type check
        run: pnpm tsc --noEmit
      
      - name: Run tests
        run: pnpm test
      
      - name: Build application
        id: build
        run: pnpm run build
      
      # テストカバレッジレポート（オプション）
      - name: Upload test coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7